# Docker-Compose document
# Ref : https://docs.docker.com/compose/compose-file/

version: "3"
services:
  consul-center:
    image: hashicorp/consul
    container_name: consul-center_${PROJECT_NAME}
    ports:
      - "8500:8500"
      - "8600:8600"
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    networks:
      - service_network

  consul-node-1:
    image: hashicorp/consul
    container_name: consul-node-1_${PROJECT_NAME}
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    command: ["agent", "-retry-join=consul-center"]
    networks:
      - service_network

  consul-node-2:
    image: hashicorp/consul
    container_name: consul-node-2_${PROJECT_NAME}
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    command: ["agent", "-retry-join=consul-center"]
    networks:
      - service_network

networks:
  service_network:
    driver: bridge
