# Docker-Compose document
# Ref : https://docs.docker.com/compose/compose-file/

version: "3"
services:
  consul-center:
    image: hashicorp/consul
    container_name: consul-center_${PROJECT_NAME}
    ports:
      - "8500:8500"
      - "8600:8600"
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    volumes:
      - ${APP_DIR}\server\center.json:/consul/config/server.json:ro
      - ${CACHE_DIR}\certs:/consul/config/certs/:ro
    networks:
      - consul

  consul-node-1:
    image: hashicorp/consul
    container_name: consul-node-1_${PROJECT_NAME}
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    volumes:
     - ${APP_DIR}\server\node-1.json:/consul/config/server.json:ro
    networks:
      - consul

  consul-node-2:
    image: hashicorp/consul
    container_name: consul-node-2_${PROJECT_NAME}
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    volumes:
     - ${APP_DIR}\server\node-2.json:/consul/config/server.json:ro
    networks:
      - consul

networks:
  consul:
    driver: bridge
