# Docker-Compose document
# Ref : https://docs.docker.com/compose/compose-file/

version: "3"
services:
  consul-server-1:
    image: hashicorp/consul
    container_name: consul-server-1_${PROJECT_NAME}
    ports:
      - "8500:8500"
      - "8600:8600"
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    volumes:
      - ${APP_DIR}\server\node-1.json:/consul/config/agent.json:ro
      - ${CACHE_DIR}\config\encrypt.json:/consul/config/encrypt.json:ro
      - ${CACHE_DIR}\config\tls-server.json:/consul/config/tls.json:ro
      - ${CACHE_DIR}\certs:/consul/certs/:ro
    networks:
      - consul

  consul-server-2:
    image: hashicorp/consul
    container_name: consul-server-2_${PROJECT_NAME}
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    volumes:
      - ${APP_DIR}\server\node-2.json:/consul/config/agent.json:ro
      - ${CACHE_DIR}\config\encrypt.json:/consul/config/encrypt.json:ro
      - ${CACHE_DIR}\config\tls-server.json:/consul/config/tls.json:ro
      - ${CACHE_DIR}\certs:/consul/certs/:ro
    networks:
      - consul

  consul-server-3:
    image: hashicorp/consul
    container_name: consul-server-3_${PROJECT_NAME}
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    volumes:
      - ${APP_DIR}\server\node-3.json:/consul/config/agent.json:ro
      - ${CACHE_DIR}\config\encrypt.json:/consul/config/encrypt.json:ro
      - ${CACHE_DIR}\config\tls-server.json:/consul/config/tls.json:ro
      - ${CACHE_DIR}\certs:/consul/certs/:ro
    networks:
      - consul

  consul-client-1:
    image: hashicorp/consul
    container_name: consul-client-1_${PROJECT_NAME}
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    volumes:
      - ${SRC_DIR}\service:/consul/src:ro
      - ${APP_DIR}\client\default\agent.json:/consul/config/agent.json:ro
      - ${APP_DIR}\client\default\services.json:/consul/config/services.json:ro
      - ${CACHE_DIR}\config\encrypt.json:/consul/config/encrypt.json:ro
      - ${CACHE_DIR}\config\tls-client.json:/consul/config/tls.json:ro
      - ${CACHE_DIR}\certs:/consul/certs/:ro
    networks:
      - consul

  consul-service-nginx:
    image: nginx
    container_name: consul-service-nginx_${PROJECT_NAME}
    networks:
      - consul

  consul-service-ttl:
    image: bash
    container_name: consul-service-ttl_${PROJECT_NAME}
    volumes:
      - ${SRC_DIR}\service:/consul/src:ro
    command: ["tail","-f","/dev/null"]
    networks:
      - consul

networks:
  consul:
    driver: bridge
